apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
    annotations:
      argocd-image-updater.argoproj.io/image-list: "springbootmongo=sganesamoorthy/project-service"
      argocd-image-updater.argoproj.io/update-strategy: "latest"
      argocd-image-updater.argoproj.io/docker-registry: "my-dockerhub-secret" # Add this linespec:
spec:
  project: default

  source:
    repoURL: https://github.com/Ganesamoorthyselvaraj/team4helm.git
    targetRevision: main
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: springbootmongo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
