---
- name: Install Argo CD Image Updater
  hosts: master
  become: yes
  tasks:
    tasks:
    - name: Create Namespace for Argo CD
      shell: kubectl create namespace argocd
      ignore_errors: yes

    - name: Apply Argo CD Image Updater Manifest
      shell: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml

    - name: Verify Argo CD Image Updater Installation
      shell: kubectl get pods -n argocd
      register: image_updater_pods

    - debug: var=image_updater_pods.stdout_lines
